services:
  api_docs:
    build: .
    container_name: api-docs
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - pharminc-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-docs.rule=Host(`docs.pharminc.in`)"
