services:
  api_docs:
    build: .
    container_name: api-docs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-docs.rule=Host(`docs.pharminc.in`)"
